## EDA

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import data_profiling

In [5]:
file_path = '../data/raw/dataset.csv'
df = pd.read_csv(file_path)

Visualisation de dataset

In [6]:
df.head()

,CUST_ID,BALANCE,PURCHASES,ONEOFF_PURCHASES,INSTALLMENTS_PURCHASES,CASH_ADVANCE,CREDIT_LIMIT,PAYMENTS
0,C10001,40.900749,95.40,0.00,95.4,0.000000,1000.0,201.802084
1,C10002,3202.467416,0.00,0.00,0.0,6442.945483,7000.0,4103.032597
2,C10003,2495.148862,773.17,773.17,0.0,0.000000,7500.0,622.066742
3,C10004,1666.670542,1499.00,1499.00,0.0,205.788017,7500.0,0.000000
4,C10005,817.714335,16.00,16.00,0.0,0.000000,1200.0,678.334763

In [7]:
df.describe(include='all')

,CUST_ID,BALANCE,PURCHASES,ONEOFF_PURCHASES,INSTALLMENTS_PURCHASES,CASH_ADVANCE,CREDIT_LIMIT,PAYMENTS
count,8950,8950.000000,8950.000000,8950.000000,8950.000000,8950.000000,8949.000000,8950.000000
unique,8950,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,C10001,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,1564.474828,1003.204834,592.437371,411.067645,978.871112,4494.449450,1733.143852
std,NaN,2081.531879,2136.634782,1659.887917,904.338115,2097.163877,3638.815725,2895.063757
min,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,50.000000,0.000000
25%,NaN,128.281915,39.635000,0.000000,0.000000,0.000000,1600.000000,383.276166
50%,NaN,873.385231,361.280000,38.000000,89.000000,0.000000,3000.000000,856.901546
75%,NaN,2054.140036,1110.130000,577.405000,468.637500,1113.821139,6500.000000,1901.134317
max,NaN,19043.138560,49039.570000,40761.250000,22500.000000,47137.211760,30000.000000,50721.483360